// Generated by CoffeeScript 1.7.1
var createStatus = function(desc, code){
  return {
    code: code,
    description:desc
  };
};

var self = {};
 
self[100] = self['CONTINUE'] = createStatus('Continue', 100);
self[101] = self['SWITCHING_PROTOCOLS'] = createStatus('Switching Protocols', 101);
self[200] = self['OK'] = createStatus('OK', 200);
self[201] = self['CREATED'] = createStatus('Created', 201);
self[202] = self['ACCEPTED'] = createStatus('Accepted', 202);
self[203] = self['NON_AUTHORITATIVE_INFORMATION'] = createStatus('Non-Authoritative Information', 203);
self[204] = self['NO_CONTENT'] = createStatus('No Content', 204);
self[205] = self['RESET_CONTENT'] = createStatus('Reset Content', 205);
self[206] = self['PARTIAL_CONTENT'] = createStatus('Partial Content', 206);
self[300] = self['MULTIPLE_CHOICES'] = createStatus('Multiple Choices', 300);
self[301] = self['MOVED_PERMANENTLY'] = createStatus('Moved Permanently', 301);
self[302] = self['FOUND'] = createStatus('Found', 302);
self[303] = self['SEE_OTHER'] = createStatus('See Other', 303);
self[304] = self['NOT_MODIFIED'] = createStatus('Not Modified', 304);
self[305] = self['USE_PROXY'] = createStatus('Use Proxy', 305);
self[307] = self['TEMPORARY_REDIRECT'] = createStatus('Temporary Redirect', 307);
self[400] = self['BAD_REQUEST'] = createStatus('Bad Request', 400);
self[401] = self['UNAUTHORIZED'] = createStatus('Unauthorized', 401);
self[402] = self['PAYMENT_REQUIRED'] = createStatus('Payment Required', 402);
self[403] = self['FORBIDDEN'] = createStatus('Forbidden', 403);
self[404] = self['NOT_FOUND'] = createStatus('Not Found', 404);
self[405] = self['METHOD_NOT_ALLOWED'] = createStatus('Method Not Allowed', 405);
self[406] = self['NOT_ACCEPTABLE'] = createStatus('Not Acceptable', 406);
self[407] = self['PROXY_AUTHENTICATION_REQUIRED'] = createStatus('Proxy Authentication Required', 407);
self[408] = self['REQUEST_TIMEOUT'] = createStatus('Request Time-out', 408);
self[409] = self['CONFLICT'] = createStatus('Conflict', 409);
self[410] = self['GONE'] = createStatus('Gone', 410);
self[411] = self['LENGTH_REQUIRED'] = createStatus('Length Required', 411);
self[412] = self['PRECONDITION_FAILED'] = createStatus('Precondition Failed', 412);
self[413] = self['REQUEST_ENTITY_TOO_LARGE'] = createStatus('Request Entity Too Large', 413);
self[414] = self['REQUEST_URI_TOO_LONG'] = createStatus('Request-URI Too Large', 414);
self[415] = self['UNSUPPORTED_MEDIA_TYPE'] = createStatus('Unsupported Media Type', 415);
self[416] = self['REQUESTED_RANGE_NOT_SATISFIABLE'] = createStatus('Requested Range not Satisfiable', 416);
self[417] = self['EXPECTATION_FAILED'] = createStatus('Expectation Failed', 417);
self[422] = self['UNPROCESSABLE_ENTITY'] = createStatus('Unprocessable Entity', 422);
self[429] = self['TOO_MANY_REQUESTS'] = createStatus('Too Many Requests', 429);
self[500] = self['INTERNAL_SERVER_ERROR'] = createStatus('Internal Server Error', 500);
self[501] = self['NOT_IMPLEMENTED'] = createStatus('Not Implemented', 501);
self[502] = self['BAD_GATEWAY'] = createStatus('Bad Gateway', 502);
self[503] = self['SERVICE_UNAVAILABLE'] = createStatus('Service Unavailable', 503);
self[504] = self['GATEWAY_TIMEOUT'] = createStatus('Gateway Time-out', 504);
self[505] = self['HTTP_VERSION_NOT_SUPPORTED'] = createStatus('HTTP Version not Supported', 505);

module.exports = self;
