// Generated by CoffeeScript 1.7.1
var createStatus = function(desc, code){
  return {
    code: code,
    description:desc
  };
};
var self = {
  CONTINUE: 100,
  SWITCHING_PROTOCOLS: 101,
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NON_AUTHORITATIVE_INFORMATION: 203,
  NO_CONTENT: 204,
  RESET_CONTENT: 205,
  PARTIAL_CONTENT: 206,
  MULTIPLE_CHOICES: 300,
  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  SEE_OTHER: 303,
  NOT_MODIFIED: 304,
  USE_PROXY: 305,
  TEMPORARY_REDIRECT: 307,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  PRECONDITION_FAILED: 412,
  REQUEST_ENTITY_TOO_LARGE: 413,
  REQUEST_URI_TOO_LONG: 414,
  UNSUPPORTED_MEDIA_TYPE: 415,
  REQUESTED_RANGE_NOT_SATISFIABLE: 416,
  EXPECTATION_FAILED: 417,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
  HTTP_VERSION_NOT_SUPPORTED: 505
};
 
self[100] = createStatus('Continue', 100);
self[101] = createStatus('Switching Protocols', 101);
self[200] = createStatus('OK', 200);
self[201] = createStatus('Created', 201);
self[202] = createStatus('Accepted', 202);
self[203] = createStatus('Non-Authoritative Information', 203);
self[204] = createStatus('No Content', 204);
self[205] = createStatus('Reset Content', 205);
self[206] = createStatus('Partial Content', 206);
self[300] = createStatus('Multiple Choices', 300);
self[301] = createStatus('Moved Permanently', 301);
self[302] = createStatus('Found', 302);
self[303] = createStatus('See Other', 303);
self[304] = createStatus('Not Modified', 304);
self[305] = createStatus('Use Proxy', 305);
self[307] = createStatus('Temporary Redirect', 307);
self[400] = createStatus('Bad Request', 400);
self[401] = createStatus('Unauthorized', 401);
self[402] = createStatus('Payment Required', 402);
self[403] = createStatus('Forbidden', 403);
self[404] = createStatus('Not Found', 404);
self[405] = createStatus('Method Not Allowed', 405);
self[406] = createStatus('Not Acceptable', 406);
self[407] = createStatus('Proxy Authentication Required', 407);
self[408] = createStatus('Request Time-out', 408);
self[409] = createStatus('Conflict', 409);
self[410] = createStatus('Gone', 410);
self[411] = createStatus('Length Required', 411);
self[412] = createStatus('Precondition Failed', 412);
self[413] = createStatus('Request Entity Too Large', 413);
self[414] = createStatus('Request-URI Too Large', 414);
self[415] = createStatus('Unsupported Media Type', 415);
self[416] = createStatus('Requested Range not Satisfiable', 416);
self[417] = createStatus('Expectation Failed', 417);
self[422] = createStatus('Unprocessable Entity', 422);
self[429] = createStatus('Too Many Requests', 429);
self[500] = createStatus('Internal Server Error', 500);
self[501] = createStatus('Not Implemented', 501);
self[502] = createStatus('Bad Gateway', 502);
self[503] = createStatus('Service Unavailable', 503);
self[504] = createStatus('Gateway Time-out', 504);
self[505] = createStatus('HTTP Version not Supported', 505);

module.exports = self;
